model_list:
  - model_name: github_copilot/GPT-5.3-Codex
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/GPT-5.1-Codex
  - model_name: github_coilot/GPT-5.4
    model_info:
      mode: responses
    litellm_params:
      model: github_copilot/GPT-5.4
  - model_name: nvidia/glm4.7
    litellm_params:
      model: nvidia_nim/z-ai/glm4.7
      api_key: "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"
  - model_name: nvidia/minimax-m2.7
    litellm_params:
      model: nvidia_nim/minimaxai/minimax-m2.7
      api_key: "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"
general_settings: 
  master_key: sk-1234
  alerting: ["slack"]
  database_url: "postgresql://postgres:asdf@host.containers.internal:5432/postgres"
